run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - exhaustruct
    - path: caller/constraints_test\.go
      linters:
        - lll
    - path: caller/caller_test\.go
      linters:
        - lll
    - path: _test\.go
      text: "var-declaration: should drop .* from declaration of .*; it is the zero value"
    - path: _test\.go
      text: "should omit type .* from declaration.*; it will be inferred from the right-hand side"

linters:
  enable-all: true
  disable:
    - funlen
    - varnamelen
    - interfacer
    - golint
    - structcheck
    - maligned
    - deadcode
    - exhaustivestruct
    - nosnakecase
    - ifshort
    - scopelint
    - varcheck
    - depguard
    - testifylint
    - nonamedreturns
    - goerr113
    - gofumpt
